export const GET_KTP = 'GET_KTP';
export const GET_REKENING = 'GET_REKENING';
export const GET_REKENING_REG = 'GET_REKENING_REG';
export const REMOVE_REKENING = 'REMOVE_REKENING';
export const SUCCESS_ORDER = 'SUCCESS_ORDER';