export default[
	{text: 'Pelajar/Mahasiswa', value: 'A'},
	{text: 'Ibu Rumah Tangga', value: 'B'},
	{text: 'Karyawan Swasta', value: 'C'},
	{text: 'Pegawai Negeri', value: 'D'},
	{text: 'TNI/POLRI', value: 'E'},
	{text: 'Pejabat Negara/Daerah', value: 'F'},
	{text: 'Pensiunan', value: 'G'},
	{text: 'Pengusaha Pabrikan', value: 'H'},
	{text: 'Pedagang', value: 'I'},
	{text: 'Pengusaha Jasa', value: 'J'},
	{text: 'Pengacara', value: 'K'},
	{text: 'Akuntan', value: 'L'},
	{text: 'Wartawan', value: 'M'},
	{text: 'Seniman', value: 'N'},
	{text: 'Notaris', value: 'O'},
	{text: 'Profesional Lainnya', value: 'P'},
	{text: 'Lainnya', value: 'Q'},
];