export default[
	{text: 'Pelajar/Mahasiswa', value: 'A', name: 'pekerjaan'},
	{text: 'Ibu Rumah Tangga', value: 'B', name: 'pekerjaan'},
	{text: 'Karyawan Swasta', value: 'C', name: 'pekerjaan'},
	{text: 'Pegawai Negeri', value: 'D', name: 'pekerjaan'},
	{text: 'TNI/POLRI', value: 'E', name: 'pekerjaan'},
	{text: 'Pejabat Negara/Daerah', value: 'F', name: 'pekerjaan'},
	{text: 'Pensiunan', value: 'G', name: 'pekerjaan'},
	{text: 'Pengusaha Pabrikan', value: 'H', name: 'pekerjaan'},
	{text: 'Pedagang', value: 'I', name: 'pekerjaan'},
	{text: 'Pengusaha Jasa', value: 'J', name: 'pekerjaan'},
	{text: 'Pengacara', value: 'K', name: 'pekerjaan'},
	{text: 'Akuntan', value: 'L', name: 'pekerjaan'},
	{text: 'Wartawan', value: 'M', name: 'pekerjaan'},
	{text: 'Seniman', value: 'N', name: 'pekerjaan'},
	{text: 'Notaris', value: 'O', name: 'pekerjaan'},
	{text: 'Profesional Lainnya', value: 'P', name: 'pekerjaan'},
	{text: 'Lainnya', value: 'Q', name: 'pekerjaan'},
];